#! /usr/bin/python3

import sys

sys.path.append('/usr/share/lliurex-perfilreset/')

import LliurexPerfilreset

if __name__=="__main__":
	
	args={}
	args["gui"]=True
	ls=LliurexPerfilreset.LliurexPerfilreset(args)